/*******************************************************************************************************************************************

    DZX | DATALINK | APP                                                                                                  VERSION 18.2.1
    ------------------------------------------------------------------------------------------------------------------------------------

    This contains handlers and definitions for parsing and processing messages received over a data link. This file has been auto
    generated by a tool and should not be manually edited.

        Definition File:      demolink.xml
        Protocol Version:     1
        Generation Date:      07/28/2016 12:29:17 PM


    ------------------------------------------------------------------------------------------------------------------------------------
    COPYRIGHT (C) 2016 DZX DESIGNS

*******************************************************************************************************************************************/
#include "DataLink/datalink_core.h"
#include "datalink_app.h"

/*******************************************************************************************************************************************
    PRIVATE FUNCTIONS
*******************************************************************************************************************************************/
static STATUS DATALINK_EnableStatusStream_Received(DATALINK* link, void* data, UINT32 nbytes);
static STATUS DATALINK_ReadMemory_Received(DATALINK* link, void* data, UINT32 nbytes);
static STATUS DATALINK_WriteMemory_Received(DATALINK* link, void* data, UINT32 nbytes);

/***************************************************************************************************************************************//**

    Creates and initializes the custom 'App' data link.

    @param[in]  link        A pointer to the target data link.
    @param[in]  write       A pointer to a handler function to write (transmit) messages for the data link.
    @param[in]  writearg    A pointer to an application-defined variable that is passed to the write handler.

    @return     None.

*******************************************************************************************************************************************/
STATUS DATALINK_CreateApp(DATALINK* link, DATALINKWRITEHANDLER write, void* writearg)
{
    ALIGNED(4) static BYTE buffer[12];                          /* Allocate a buffer for unsolicited messages */
    STATUS status;


#if (CFG_NULLCHECKING)
    if (write == NULL) {
        return ERR_NULLREFERENCE;
    }
#endif

    status = DATALINK_Create(link, write, writearg);            /* Initialize the base link */
    if (status != SUCCESS) {
        return status;
    }

    link->version = 1;
    link->useCRC = FALSE;
    link->buffer = buffer;

    return SUCCESS;
}

/***************************************************************************************************************************************//**

    Processes a received encapsulated message.

    @param[in]  link        A pointer to the target data link.
    @param[in]  id          The message identifier for the data.
    @param[in]  data        A pointer to the data that has been received.
    @param[in]  nbytes      The total number of bytes that have been received.

    @return

     Status                 | Description
    ----------------------- | ------------------------------------------------------------------------------------------------------
     SUCCESS                | The message has been processed.
     ERR_NOTSUPPORTED       | The message was not supported.
     ERR_CORRUPTED          | The message has failed CRC verification and is considered to be corrupted.

*******************************************************************************************************************************************/
STATUS DATALINK_HandleMessage(DATALINK* link, DATALINKID id, void* data, UINT32 nbytes)
{
    switch (id.number) {
        case MSGID_ENABLESTATUSSTREAM:
            return DATALINK_EnableStatusStream_Received(link, data, nbytes);
        case MSGID_READMEMORY:
            return DATALINK_ReadMemory_Received(link, data, nbytes);
        case MSGID_WRITEMEMORY:
            return DATALINK_WriteMemory_Received(link, data, nbytes);
    }

    return ERR_NOTSUPPORTED;
}

/***************************************************************************************************************************************//**

    A handler called when the 'Enable Status Stream' message has been received.

    @param[in]  link        A pointer to the target data link.
    @param[in]  data        A pointer to the data that has been received.
    @param[in]  nbytes      The size, in bytes, of the message data.

    @return

     STATUS                 | Description
    ----------------------- | ------------------------------------------------------------------------------------------------------
     SUCCESS                | The message has been processed.

*******************************************************************************************************************************************/
static STATUS DATALINK_EnableStatusStream_Received(DATALINK* link, void* data, UINT32 nbytes)
{
    ENABLESTATUSSTREAMARGS args;
    UINT32 offset;


    offset = sizeof(DATALINKID);
    args.enabled = ((BYTE*)data)[offset++];

    DATALINK_EnableStatusStream_Handler(link, &args);

    return SUCCESS;
}

/***************************************************************************************************************************************//**

    A handler called when the 'Read Memory' message has been received.

    @param[in]  link        A pointer to the target data link.
    @param[in]  data        A pointer to the data that has been received.
    @param[in]  nbytes      The size, in bytes, of the message data.

    @return

     STATUS                 | Description
    ----------------------- | ------------------------------------------------------------------------------------------------------
     SUCCESS                | The message has been processed.

*******************************************************************************************************************************************/
static STATUS DATALINK_ReadMemory_Received(DATALINK* link, void* data, UINT32 nbytes)
{
    REQUEST_READMEMORY request;
    RESPONSE_READMEMORY response;
    STATUS status;
    UINT32 offset;
    UINT32 k;


    offset = sizeof(DATALINKID);
    offset += DATALINK_Deserialize(data, offset, &request.address, sizeof(UINT32));
    offset += DATALINK_Deserialize(data, offset, &request.length, sizeof(UINT32));

    memset(&response, 0, sizeof(RESPONSE_READMEMORY));

    DATALINK_ReadMemory_Handler(link, &request, &response);

    offset = sizeof(DATALINKID);
    if (response.data.count > 256) {
        response.data.count = 256;
    }
    offset += DATALINK_Serialize(data, offset, &response.data.count, sizeof(UINT16));

    for (k = 0; k < response.data.count; k++) {
        offset += DATALINK_Serialize(data, offset, &response.data.values[k], sizeof(UINT8));
    }
    offset += DATALINK_Serialize(data, offset, &response.result, sizeof(UINT32));

    status = DATALINK_Write(link, data, offset);                /* Send the response to the host */
    if (status != SUCCESS) {
        return status;
    }

    return SUCCESS;
}

/***************************************************************************************************************************************//**

    A handler called when the 'Write Memory' message has been received.

    @param[in]  link        A pointer to the target data link.
    @param[in]  data        A pointer to the data that has been received.
    @param[in]  nbytes      The size, in bytes, of the message data.

    @return

     STATUS                 | Description
    ----------------------- | ------------------------------------------------------------------------------------------------------
     SUCCESS                | The message has been processed.

*******************************************************************************************************************************************/
static STATUS DATALINK_WriteMemory_Received(DATALINK* link, void* data, UINT32 nbytes)
{
    REQUEST_WRITEMEMORY request;
    RESPONSE_WRITEMEMORY response;
    STATUS status;
    UINT32 offset;
    UINT32 k;


    offset = sizeof(DATALINKID);
    offset += DATALINK_Deserialize(data, offset, &request.address, sizeof(UINT32));
    offset += DATALINK_Deserialize(data, offset, &request.data.count, sizeof(UINT16));

    if (request.data.count > 256) {
        request.data.count = 256;
    }

    for (k = 0; k < request.data.count; k++) {
        offset += DATALINK_Deserialize(data, offset, &request.data.values[k], sizeof(UINT8));
    }

    memset(&response, 0, sizeof(RESPONSE_WRITEMEMORY));

    DATALINK_WriteMemory_Handler(link, &request, &response);

    offset = sizeof(DATALINKID);
    offset += DATALINK_Serialize(data, offset, &response.result, sizeof(UINT32));

    status = DATALINK_Write(link, data, offset);                /* Send the response to the host */
    if (status != SUCCESS) {
        return status;
    }

    return SUCCESS;
}

/***************************************************************************************************************************************//**

    

    @param[in]  link        A pointer to the target data link.
    @param[in]  arg         

    @return     None.

*******************************************************************************************************************************************/
STATUS DATALINK_DeviceStatus(DATALINK* link, const DEVICESTATUSARGS* arg)
{
    STATUS status;
    UINT32 offset;
    DATALINKID id;


    status = MUTEX_Acquire(&link->mutex, INFINITE);
    if (status != SUCCESS) {
        return status;
    }

    id.value = 0;
    id.number = MSGID_DEVICESTATUS;

    offset = 0;
    offset += DATALINK_Serialize(link->buffer, offset, &id, sizeof(DATALINKID));
    offset += DATALINK_Serialize(link->buffer, offset, &arg->kernelUtilization, sizeof(UINT32));
    offset += DATALINK_Serialize(link->buffer, offset, &arg->kernelTicks, sizeof(UINT32));

    status = DATALINK_Write(link, link->buffer, offset);
    if (status != SUCCESS) {
        MUTEX_Release(&link->mutex);
        return status;
    }

    MUTEX_Release(&link->mutex);
    return SUCCESS;
}

