/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.9.0
 *
 * Project: 'Project+GD32E230GSTART' 
 * Target:  'GD32E230GSTART' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "gd32e23x.h"



#endif /* RTE_COMPONENTS_H */
